micronaut-projects/micronaut-test

test-spock/src/test/groovy/io/micronaut/test/spock/PropertySourceSpec.groovy
=> Remove redundant @Inject

test-kotlintest/src/main/kotlin/io/micronaut/test/extensions/kotlintest/MicronautKotlinTestExtension.kt, test-kotlintest/src/test/kotlin/io/kotlintest/provided/ProjectConfig.kt, test-kotlintest/src/test/kotlin/io/micronaut/test/kotlintest/ApplicationRunAnotherTest.kt, test-kotlintest/src/test/kotlin/io/micronaut/test/kotlintest/MathCollaboratorTest.kt, test-kotlintest/src/test/kotlin/io/micronaut/test/kotlintest/MathMockServiceTest.kt, test-kotlintest/src/test/kotlin/io/micronaut/test/kotlintest/MathServiceTestSimilarNameTest.kt
Addresses https://github.com/micronaut-projects/micronaut-test/issues/55#issuecomment-517400821
=> Fix typo in file and classname

test-spock/src/main/java/io/micronaut/test/extensions/spock/MicronautSpockExtension.java, test-spock/src/test/groovy/io/micronaut/test/spock/FixtureWithAnnotationSpec.groovy
This will resolve bug reported in issue #71
=> Call proceed on `cleanupSpec` method invocation

gradle.properties, src/main/docs/guide/junit5.adoc, src/main/docs/guide/kotlintest.adoc, src/main/docs/guide/spock.adoc, test-core/build.gradle, test-core/src/main/java/io/micronaut/test/annotation/MicronautTest.java, test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java, test-junit5/build.gradle, test-junit5/src/main/java/io/micronaut/test/extensions/junit5/MicronautJunit5Extension.java, test-junit5/src/test/java/io/micronaut/test/junit5/PropertyValueRequiresTest.java, test-junit5/src/test/java/io/micronaut/test/junit5/PropertyValueTest.java, test-kotlintest/build.gradle, test-kotlintest/src/main/kotlin/io/micronaut/test/extensions/kotlintest/MicronautKotlinTestContext.kt, test-kotlintest/src/test/kotlin/io/micronaut/test/kotlintest/PropertyValueRequiresTest.kt, test-kotlintest/src/test/kotlin/io/micronaut/test/kotlintest/PropertyValueTest.kt, test-kotlintest/src/test/resources/logback.xml, test-spock/src/main/java/io/micronaut/test/extensions/spock/MicronautSpockExtension.java, test-spock/src/test/groovy/io/micronaut/test/spock/PropertyValueRequiresSpec.groovy, test-spock/src/test/groovy/io/micronaut/test/spock/PropertyValueSpec.groovy
Fixes #91.
@jameskleeh the Kotlin version isn't working. Would need to chat with you about it.
=> Rebuild the context if there are property changes

gradle.properties, test-bom/build.gradle, test-kotest/build.gradle, test-kotlintest/build.gradle
Fixes https://github.com/micronaut-projects/micronaut-core/issues/2298
=> Add Kotlintest and Kotest dependencies to the BOM

test-core/src/main/java/io/micronaut/test/annotation/MicronautTest.java
Current documentation might suggest that @MicronautTest works only with Spock although it also works with JUnit 5.
=> Note that @MicronautTest also works with JUnit 5

test-spock/src/main/java/io/micronaut/test/extensions/spock/MicronautSpockExtension.java, test-spock/src/test/groovy/io/micronaut/test/spock/SharedInjectionSpec.groovy
=> Fix injection of shared fields from superclass

src/main/docs/guide/introduction.adoc, src/main/docs/guide/releaseHistory.adoc, src/main/docs/guide/toc.yml
=> Add Release History section

test-bom/build.gradle
Close: https://github.com/micronaut-projects/micronaut-test/issues/261
=> buidl: add kotest-assertions-core-jvm to test bom

test-junit5/src/test/java/io/micronaut/test/junit5/Simple1Test.java, test-junit5/src/test/java/io/micronaut/test/junit5/Simple2Test.java, test-junit5/src/test/java/io/micronaut/test/junit5/SimpleBaseTest.java, test-junit5/src/test/java/io/micronaut/test/junit5/SimpleService.java, test-junit5/src/test/java/io/micronaut/test/junit5/SimpleServiceInterface.java, test-junit5/src/test/java/io/micronaut/test/junit5/SimpleWorker.java, test-junit5/src/test/resources/logback.xml
This PR has tests to prove that #223 is in fact a duplicate of #123 
See commit 1370daf
Closes #223
=> Tests for #223

test-core/src/main/java/io/micronaut/test/annotation/MicronautTest.java, test-core/src/main/java/io/micronaut/test/annotation/TransactionMode.java, test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java, test-core/src/main/java/io/micronaut/test/transaction/spring/SpringTransactionTestExecutionListener.java, test-junit5/src/test/java/io/micronaut/test/junit5/JpaSingleTransactionMultipleSetupsTest.java, test-junit5/src/test/java/io/micronaut/test/junit5/JpaSingleTransactionNoSetupTest.java, test-junit5/src/test/java/io/micronaut/test/junit5/JpaSingleTransactionTest.java, test-spock/src/main/java/io/micronaut/test/extensions/spock/MicronautSpockExtension.java, test-spock/src/test/groovy/io/micronaut/test/spock/GormTransactionalSingleTransactionSpec.groovy
Implements https://github.com/micronaut-projects/micronaut-test/issues/238
=> Add option to @MicronautTest to allow wrapping of setup and tests in a single transaction

src/main/docs/guide/includes/transaction.adoc, src/main/docs/guide/spock.adoc
Closes https://github.com/micronaut-projects/micronaut-test/issues/268.
=> Document @MicronautTest transaction modes

test-core/src/main/java/io/micronaut/test/condition/TestActiveCondition.java, test-junit5/src/test/java/io/micronaut/test/junit5/SimpleBaseTest.java, test-junit5/src/test/java/io/micronaut/test/junit5/SimpleService.java, test-junit5/src/test/java/io/micronaut/test/junit5/SimpleServiceInterface.java
Fixes https://github.com/micronaut-projects/micronaut-test/issues/223
=> Fix test active conditions for beans defined in super class

gradle.properties, test-bom/build.gradle
adding test-bom entries for Mockito, Assertj, Hamcrest to support corresponding micronaut-starter features
=> adding test-bom entries

test-bom/build.gradle
=> Issue 397 - adding mockito-junit-jupiter module

test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java, test-junit5/src/test/java/io/micronaut/test/junit5/FirstExecutionListener.java, test-junit5/src/test/java/io/micronaut/test/junit5/SecondExecutionListener.java
=> Reverse listeners after test execution so cleanup happens in order

test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java, test-junit5/src/test/java/io/micronaut/test/junit5/PropertyValueTest.java, test-junit5/src/test/resources/application-test.yml, test-kotest/src/test/kotlin/io/micronaut/test/kotest/PropertyValueTest.kt, test-kotest/src/test/resources/application-test.yml, test-spock/src/test/groovy/io/micronaut/test/spock/PropertySpec.groovy, test-spock/src/test/resources/application-test.yml
=> Fix property override from config

test-junit5/src/main/java/io/micronaut/test/extensions/junit5/MicronautJunit5Extension.java, test-spock/src/main/java/io/micronaut/test/extensions/spock/MicronautSpockExtension.java
=> Calculate injection point names

test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java, test-junit5/src/test/java/io/micronaut/test/junit5/PropertyClassTest.java
=> Don't set null values in the testProperties

gradle.properties
This should have be done prior to https://github.com/micronaut-projects/micronaut-test/releases/tag/v3.1.0
=> ci: change githubCoreBranch to 3.4.x

src/main/docs/guide/introduction.adoc
- Kotest uses a separate annotation from JUnit
- Also update order to reflect order of sections in docs
=> Update annotation reference in introduction.adoc

src/main/docs/guide/junit5.adoc
Small grammar correction to note about using `TestPropertyProvider`.
=> Fix grammatical typo

gradle.properties, test-kotest5/build.gradle
- `micronautVersion` to `3.4.3`
- `groovyVersion` to `3.0.10`
- `githubCoreBranch` to `3.5.x`
=> ci: projectVersion to 3.2.0-SNAPSHOT

src/main/docs/guide/kotest5.adoc
=> Update ProjectConfig.kt in Kotest5 documentation

gradle/libs.versions.toml
- [build: mockito monorepo to v4.8.0](https://github.com/micronaut-projects/micronaut-test/commit/a0034986ce007b5322de6715175a8662cd6a89bd)
- [build: Micronaut 3.6.3](https://github.com/micronaut-projects/micronaut-test/commit/865fcf7516ae4b4ff23994a0ae76806a830697e4)
- [build: KoTest 5.4.2 from 5.4.1](https://github.com/micronaut-projects/micronaut-test/commit/72220b1d4dbe928fa27e18b2912aa180fc56363e)
=> build: update Mockito, Kotest and Micronaut 

src/main/docs/guide/kotest.adoc
Co-authored-by: @joostlek via https://github.com/micronaut-projects/micronaut-test/pull/662
=> Fix anchor link

test-core/src/main/java/io/micronaut/test/annotation/MicronautTestValue.java, test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java, test-junit5/src/main/java/io/micronaut/test/extensions/junit5/MicronautJunit5Extension.java, test-junit5/src/main/java/io/micronaut/test/extensions/junit5/annotation/MicronautTest.java, test-junit5/src/test/java/io/micronaut/test/junit5/FooTest.java, test-kotest/src/main/kotlin/io/micronaut/test/extensions/kotest/MicronautKotestExtension.kt, test-kotest5/src/main/kotlin/io/micronaut/test/extensions/kotest5/MicronautKotest5Extension.kt, test-spock/src/main/java/io/micronaut/test/extensions/spock/MicronautSpockExtension.java
=> add ability to disable bean resolution for parameters in JUnit 5

gradle/libs.versions.toml
Prior to doing an M2 release of this module
=> Update dependencies to latest milestones

gradle/libs.versions.toml, settings.gradle
To fix docs publication.
Also update Groovy whilst I'm passing
=> Update settings plugin

gradle/libs.versions.toml
=> Add core BOM

test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java, test-junit5/src/test/java/io/micronaut/test/junit5/PropertyMethodBeanTest.java, test-junit5/src/test/java/io/micronaut/test/junit5/PropertyMethodRebuildContextTest.java
Fixes https://github.com/micronaut-projects/micronaut-test/issues/872
=> Fix first method with `@Property` not refreshing context

test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java
=> Mention the annotation config when misconfigured
