micronaut-projects/micronaut-test

- src/main/docs/guide/introduction.adoc
Add additional notes for including the dependencies for appropriate libraries that are present, even when only using the annotation in a spock test (for example).
See https://github.com/micronaut-projects/micronaut-core/issues/979 for reason behind this change
> Mention including all dependencies required for any test framework present

- test-junit5/src/main/java/io/micronaut/test/extensions/junit5/MicronautJunit5Extension.java
- test-junit5/src/test/java/io/micronaut/test/junit5/ApplicationRunTest.java
- test-junit5/src/test/java/io/micronaut/test/junit5/MicronautAndMockitoTest.java
Hello,
I found a little issue when using `@MicronautTest` as a **meta**-annotation on a test class.
For example this kind of annotation:
```java
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.ANNOTATION_TYPE, ElementType.TYPE})
@MicronautTest
@ExtendWith(MockitoExtension.class)
public @interface MicronautAndMockitoTest {}
```
On a test class, leads to the test being ignored due to `AbstractMicronautExtension#DISABLED_MESSAGE`.
So here is a little fix 😃
> Make @MicronautTest discovered when used as meta-annotation

- test-core/src/main/java/io/micronaut/test/annotation/AnnotationUtils.java
- test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java
- test-junit5/src/test/java/io/micronaut/test/junit5/DbProperties.java
- test-junit5/src/test/java/io/micronaut/test/junit5/JpaNoRollbackTest.java
- test-junit5/src/test/java/io/micronaut/test/junit5/JpaRollbackTest.java
This is a proposal for #10.
- I am not confortable adding `@author` since this is mainly copied from the JUnit team work, what is the project policy about this ?
- Should I add the mention `@since 1.0` to the new class since version **1.0.0** is already released ?
- Since there is no test framework in **test-core**, is it okay if there is no tests for the new utility method `AnnotationUtils#findRepeatableAnnotations` ?
> Make @Property discovered when used as meta-annotation

- src/main/docs/guide/junit5.adoc
In order to run junit5 tests we need to [add a test engine](https://junit.org/junit5/docs/current/user-guide/#running-tests-build-gradle-engines-configure) to the gradle dependencies.
> Add junit5 test engine to gradle dependencies

- test-core/src/main/java/io/micronaut/test/annotation/MicronautTest.java
- test-junit5/src/test/java/io/micronaut/test/junit5/BaseTest.java
- test-junit5/src/test/java/io/micronaut/test/junit5/MathInheritedTest.java
* Added `@Inherited` to MicronautTest annotation.
* Fix JUnit ignores tests when using `@MicronautTest` in a superclass.
> Fixes #35 JUnit ignores tests when using `@MicronautTest` in a superclass

- test-spock/src/test/groovy/io/micronaut/test/spock/MathService.java
The `@Singleton` doesn't make sense in an interface.
> doc: remove `@Singleton` from interface

- test-junit5/src/main/java/io/micronaut/test/extensions/junit5/MicronautJunit5Extension.java
As discussed in #145, the ApplicationContext is now being saved into JUnit5 store.
This makes it possible for other JUnit5 extensions to retrieve current application context making it easier to integrate Micronaut with other JUnit5 extensions.
With the application context available in the store I was able to retrieve the datasource in the [dbunit extension](https://github.com/database-rider/database-rider/blob/472c19b22b679dce9cc9883fd022ca3e2251e170/rider-junit5/src/main/java/com/github/database/rider/junit5/DBUnitExtension.java#L261) and then use it in Micronaut test, see an [example here](https://github.com/rmpestano/rider-micronaut/blob/master/src/test/java/example/repositories/PetRepositoryTest.java#L26).
I didn't add a test because testing [JUnit5 …
> Saves applicationContext into junit5 store

- test-core/src/main/java/io/micronaut/test/context/TestContext.java
- test-core/src/main/java/io/micronaut/test/context/TestExecutionListener.java
- test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java
- test-core/src/main/java/io/micronaut/test/transaction/TestTransactionInterceptor.java
- test-core/src/main/java/io/micronaut/test/transaction/TestTransactionInterceptorListener.java
- test-core/src/main/java/io/micronaut/test/transaction/spring/SpringTransactionTestExecutionListener.java
- test-junit5/src/main/java/io/micronaut/test/extensions/junit5/MicronautJunit5Extension.java
- test-junit5/src/test/java/io/micronaut/test/junit5/NonTransactionalTest.java
- test-junit5/src/test/java/io/micronaut/test/junit5/TransactionalTest.java
- test-kotest/src/main/kotlin/io/micronaut/test/extensions/kotest/MicronautKotestContext.kt
- test-kotest/src/main/kotlin/io/micronaut/test/extensions/kotest/MicronautKotestExtension.kt
- test-kotest/src/test/kotlin/io/micronaut/test/kotest/NonTransactionalTest.kt
- test-kotest/src/test/kotlin/io/micronaut/test/kotest/TransactionalTest.kt
- test-kotlintest/src/main/kotlin/io/micronaut/test/extensions/kotlintest/MicronautKotlinTestContext.kt
- test-kotlintest/src/main/kotlin/io/micronaut/test/extensions/kotlintest/MicronautKotlinTestExtension.kt
- test-spock/src/main/java/io/micronaut/test/extensions/spock/MicronautSpockExtension.java
- test-spock/src/test/groovy/io/micronaut/test/spock/GormTransactionalRollbackSpec.groovy
Resolve #163 
This is a first attempt to deprecate `TestTransactionInterceptor ` and use a more complete `TestExecutionListener` instead. I lack experience with both Kotest & Spock, so I'm really looking for feedback on this PR.
> Add support for TestExecutionListener

- test-spock/src/main/java/io/micronaut/test/extensions/spock/MicronautSpockExtension.java
- test-spock/src/test/groovy/io/micronaut/test/spock/DetachedMathServiceSingletonSpec.groovy
Spock mocks/stubs don't need to be refreshable and can be singletons and be reused.
> Allow detached singleton Spock mocks

- test-core/src/main/java/io/micronaut/test/context/TestExecutionListener.java
- test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java
- test-core/src/main/java/io/micronaut/test/transaction/spring/SpringTransactionTestExecutionListener.java
- test-junit5/src/main/java/io/micronaut/test/extensions/junit5/MicronautJunit5Extension.java
- test-junit5/src/test/java/io/micronaut/test/junit5/TransactionalTest.java
- test-spock/src/main/java/io/micronaut/test/extensions/spock/MicronautSpockExtension.java
- test-spock/src/test/groovy/io/micronaut/test/spock/GormTransactionalRollbackSpec.groovy
> Add transactions to setup / cleanup to restore 1.x behaviour

- gradle.properties
This change can be reverted once we upgrade Micronaut Test to Micronaut 2.0
> Do not include `spockVersion` in PRs send to core

- gradle.properties
- src/main/docs/guide/kotest.adoc
Hey there, I would like to bump kotest's version to 4.1.3, because the testcontainers extension of kotest is supported only from version 4.1.*
> Bump kotest version to 4.1.3

- src/main/docs/guide/junit5.adoc
Factory Replacement is required for mocking Factory Injected Beans.
Added documentation to state that fact.
> Added Factory Replacement to Mockito Mocks

- gradle.properties
- test-core/build.gradle
- test-core/src/main/java/io/micronaut/test/support/server/TestEmbeddedServer.java
- test-junit5/src/test/java/io/micronaut/test/junit5/server/ExternalServerTest.java
This PR allows Micronaut test to use an embedded server that is already running, for example if the build tool (maven or gradle) were to start the server another way prior to test execution
> Allow Micronaut Test to run against an external server

- test-core/build.gradle
- test-core/src/main/java/io/micronaut/test/annotation/MicronautTestValue.java
- test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java
- test-core/src/main/java/io/micronaut/test/support/server/TestEmbeddedServer.java
- test-core/src/main/java/io/micronaut/test/support/server/TestExecutableEmbeddedServer.java
- test-junit5/src/test/java/io/micronaut/test/junit5/server/ProcessServerTest.java
This PR takes a slightly different approach and moves the management of the process into `micronaut-test` such that it can propagate test properties to the embedded server that is split out as a process. This approach is maybe more compatible with the Maven plugin as all the build plugins have to do is pass the location of the native image using the `micronaut.test.server.executable` system property.
> Allow micronaut test to manage execution of external process server

- test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java
- test-junit5/src/main/java/io/micronaut/test/extensions/junit5/MicronautJunit5Extension.java
Helps solve #330 
This is sort of a "companion MR" to [this](https://github.com/micronaut-projects/micronaut-aws/pull/748), where I'm trying to provide a `@MicronautLambdaTest` that sets up an ApplicationContext with the right configuration (eager singletons, etc.). It basically just opens up some parts of  the logic to overriding so we can achieve maximum reuse in `MicronautLambdaJunit5Extension`.
> Make MicronautJunit5Extension easier to extend

- test-junit5/src/main/java/io/micronaut/test/extensions/junit5/MicronautJunit5Extension.java
- test-junit5/src/test/java/io/micronaut/test/junit5/FirstExecutionListener.java
- test-junit5/src/test/java/io/micronaut/test/junit5/NestedTestClassesTest.java
- test-junit5/src/test/java/io/micronaut/test/junit5/SecondExecutionListener.java
- test-junit5/src/test/java/io/micronaut/test/junit5/TestExecutionListenerOrderTest.java
Fixes https://github.com/micronaut-projects/micronaut-test/issues/56.
Basic support for nested test classes is added by injecting the enclosing test instances of nested test instances.
Note: The test execution listeners that are used to verify the order of callbacks (FirstExecutionListener and SecondExecutionListener) were scoped to a specific test class (TestExecutionListenerOrderTest) since they would fail for nested test classes. This is because the before and after all callbacks of JUnit extensions are executed both for top-level and nested classes, which produces the following execution order:
1. FirstExecutionListener.beforeTestClass
2. SecondExecutionListener.beforeTestClass
3. FirstExecutionListener.beforeTestClass
In this scenario, the second …
> Add support for JUnit 5 nested test classes

- test-junit5/src/main/java/io/micronaut/test/extensions/junit5/MicronautJunit5Extension.java
- test-junit5/src/test/java/io/micronaut/test/junit5/MultipleNestedTestClassesTest.java
- test-junit5/src/test/java/io/micronaut/test/junit5/NestedTestClassesDependencyInjectionTest.java
Closes https://github.com/micronaut-projects/micronaut-test/issues/420
> MicronautJunit5Extension: do not tear down application context in afterAll callback of nested test classes

- test-junit5/src/main/java/io/micronaut/test/extensions/junit5/MicronautJunit5Extension.java
- test-junit5/src/test/java/io/micronaut/test/junit5/ConstructorInjectionTest.java
Currently `@Client` and generic argument handling is broken for constructor injection. This fixes that.
> Fix injecting correct client with constructor arguments

- test-core/src/main/java/io/micronaut/test/support/server/TestExecutableEmbeddedServer.java
@jameskleeh @ilopmar the `testNativeImage` command is broken since in core the netty server is now a `@Primary`, perhaps this was a breaking change in core, but we need mitigation as it is breaking a lot of downstream builds. Could we get this into the next patch release?
> fix testNativeImage

- test-junit5/src/main/resources/META-INF/native-image/io.micronaut.test/micronaut-test-junit5/native-image.properties
Using `./gradlew nativeTest` currently doesn't work with JUnit 5 tests annotated with `@MicronautTest`
This fixes that.
> fix micronaut-test for native JUnit 5 testing

- build.gradle
- gradle.properties
- settings.gradle
- test-bom/build.gradle
- test-core/build.gradle
- test-junit5/build.gradle
- test-kotest/build.gradle
- test-spock/build.gradle
- Removed the workaround for secure hashes (fixed in maven central)
- Reinstated the daemon
- Added parallel
Will fail currently as the docs are invalid in places (which is fixed once #509 is merged
> Update build to latest infrastructure

- test-junit5/src/main/java/io/micronaut/test/extensions/junit5/MicronautJunit5Extension.java
- test-junit5/src/test/java/io/micronaut/test/junit5/MathMockServiceNestedTest.java
If using nested tests in Junit5 injecting the mocks breaks because:
- The specDefintion reflects the root test class but
- The fields that should be injected are present on the specDefinition
- The instance object reflects the innermost test class where the fields are not present
> Use the correct test instance for injecting mocks in case of nested tests

- test-core/src/main/java/io/micronaut/test/annotation/MockBean.java
- test-junit5/src/test/java/io/micronaut/test/junit5/MathFieldMockServiceTest.java
- test-junit5/src/test/java/io/micronaut/test/junit5/MathMockFieldCollaboratorTest.java
- test-junit5/src/test/java/io/micronaut/test/junit5/MockitoCondition.java
- test-junit5/src/test/java/io/micronaut/test/junit5/MockitoEnabled.java
- test-spock/src/test/groovy/io/micronaut/test/spock/MathFieldCollaboratorSpec.groovy
Micronaut 3.3 I believe introduced the ability to use fields as beans. This makes it possible to use `@MockBean` on a field which makes the test easier to read and is less verbose
> allow mocks to be produced from fields

- test-core/src/main/java/io/micronaut/test/context/TestMethodInterceptor.java
- test-core/src/main/java/io/micronaut/test/context/TestMethodInvocationContext.java
- test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java
- test-junit5/src/main/java/io/micronaut/test/extensions/junit5/MicronautJunit5Extension.java
- test-junit5/src/test/java/io/micronaut/test/junit5/intercept/InterceptTestTest.java
- test-junit5/src/test/java/io/micronaut/test/junit5/intercept/TestInterceptor.java
- test-spock/src/main/java/io/micronaut/test/extensions/spock/MicronautSpockExtension.java
- test-spock/src/test/groovy/io/micronaut/test/spock/MathService.java
- test-spock/src/test/groovy/io/micronaut/test/spock/intercept/InterceptTestSpec.groovy
- test-spock/src/test/groovy/io/micronaut/test/spock/intercept/TestInterceptor.groovy
There is a way to support Reactive/Async transactions for `@MicronautTest` using blocking but not every API supports splitting the start and end of the call like `before/after` ~ `begin/commit` so I need the interceptor for that.
The solution doesn't work for Kotest as it only exposes begin/end API.
Maybe there is a way to use the Micronaut method-interception...
> Add API to intercept the test method

- test-junit5/src/main/java/io/micronaut/test/extensions/junit5/MicronautJunit5Extension.java
Close https://github.com/micronaut-projects/micronaut-test/issues/640
With Micronaut 3.6.3-SNAPSHOT
```
./gradlew testClasses
ls build/classes/java/test/example/micronaut/
$FruitDuplicationExceptionHandlerTest$Definition$Exec.class
$FruitDuplicationExceptionHandlerTest$Definition$Reference.class
$FruitDuplicationExceptionHandlerTest$Definition.class
FruitDuplicationExceptionHandlerTest.class
```
With Micronaut 3.7.0-SNAPSHOT
```
./gradlew testClasses
ls build/classes/java/test/example/micronaut/
$FruitDuplicationExceptionHandlerTest$Definition$Exec.class
$FruitDuplicationExceptionHandlerTest$Definition$Intercepted$Definition$Reference.class
$FruitDuplicationExceptionHandlerTest$Definition$Intercepted$Definition.class
$FruitDuplicationExceptionHandlerTest$Definition$Intercepted.class …
```
> fix: For Intercepted junit5 evalExecution disabled

- gradle.properties
- gradle/libs.versions.toml
- test-kotest/build.gradle
- test-kotest5/build.gradle
Predictive Test Selection doesn't support Kotest, so it silently skips all the tests.
This change re-instates the tests by disabling it for our 2 kotest testsuites.
> Disable PTS for kotest tests

- test-junit5/build.gradle
NativeTest was failing on Master since the Kotest removal and upgrade to Groovy 4.
https://github.com/micronaut-projects/micronaut-test/actions/runs/3219707539
> Fix nativeTest with Groovy 4

- test-kotest5/build.gradle
Starting with v3.11.2 of the Gradle Enterprise Gradle plugin, PTS
detects unsupported test engines and fails test discovery for Kotest
since it's not yet supported.
> Update reason for disabling Predictive Test Selection

- src/main/docs/guide/junit5.adoc
Without JUnit-Jupiter-Params dependency, @ParameterizedTest annotation is not available to the implementation test classes.
> Adding JUnit-Jupiter Params dependency

- settings.gradle
- test-junit5/build.gradle
When we use 'io.micronaut.library', we end up with multiple POMs in the published POM we generate.
We were using this to get nativeTest to pass.  Switching this to 'io.micronaut.graalvm' still allows this.
But it does not generate an invalid POM
Also updated the shared setting plugin whilst I was here
> Fix publication on the 4.0.0 branch

- .github/workflows/graalvm.yml
- src/main/docs/guide/introduction.adoc
- test-junit5/src/test/java/io/micronaut/test/junit5/EagerInitializationTest.java
it was found in #715 that setting eagerInitSingletons to true makes it impossible to inject an HttpClient.
This is because MicronautTest is implicitly a Singleton, so gets initialised before the embedded server.
This PR documents this fact, and provides a workaround.
Closes #715
> Document how to get an HttpClient when singletons are eagerly initialised

- gradle/libs.versions.toml
This reverts the prior mockk 1.13.4 update due to breaking change. mockk 1.12.28 to 1.13.3 uses kotlin 1.17.20 and mockk 1.13.4 changes that to kotlin 1.8.0. See https://github.com/mockk/mockk/blob/cac70d917c4cd37c9390bb3661650f6b4f09277c/buildSrc/src/main/kotlin/buildsrc/config/Deps.kt#LL14C19-L14C19, which introduces a binary incompatibility. 
1.13.3 is the last version that can be used until Micronaut 4.x (which uses kotlin 1.8+).
> Revert mockk for kotlin 1.8

- gradle/libs.versions.toml
This version of Kotest supports Predictive Tests (so we can undo https://github.com/micronaut-projects/micronaut-core/pull/8612)
**It requires Kotlin 1.8+ so needs to be for Micronaut 4.0.0**
> Upgrade to Kotest 5.6.0

- test-core/build.gradle
- test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java
- test-core/src/main/java/io/micronaut/test/support/TestPropertyProviderFactory.java
- test-core/src/testFixtures/java/io/micronaut/test/core/fixtures/DummyTestPropertyProvider.java
- test-core/src/testFixtures/java/io/micronaut/test/core/fixtures/DummyTestPropertyProviderFactory.java
- test-core/src/testFixtures/resources/META-INF/services/io.micronaut.test.support.TestPropertyProviderFactory
- test-junit5/build.gradle
- test-junit5/src/test/java/io/micronaut/test/junit5/props/TestPropertyProviderFactoryTest.java
- test-junit5/src/test/resources/application-testenv1.yml
- test-kotest5/build.gradle
- test-kotest5/src/test/kotlin/io/micronaut/test/kotest5/TestPropertiesFactoryCtorInjectionTest.kt
- test-kotest5/src/test/kotlin/io/micronaut/test/kotest5/TestPropertiesFactoryTest.kt
- test-spock/build.gradle
- test-spock/src/test/groovy/io/micronaut/test/spock/props/TestPropertiesProviderFactoryTest.groovy
This commit introduces a new way to supply test properties to tests, by implementing a `TestPropertyProviderFactory`. These factories are loaded via service loading and are responsible for instantiating a `TestPropertyProvider`.
In order to be able to dynamically provide properties, the factory is provided with the current test class, and the set of properties which are already available at the moment the provider is called.
This means that contrary to a typical `TestPropertyProvider`, this provider has access to "raw" configuration, as supplied by `PropertySourceLoader`.
This will permit the implementation of a new test resources module which will be capable of dynamically supplying test properties to test classes _before_ the application context is available, and without having to …
> Add dynamic registration of test property providers

- test-core/src/main/java/io/micronaut/test/context/TestContext.java
- test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java
- test-junit5/src/main/java/io/micronaut/test/extensions/junit5/MicronautJunit5Extension.java
- test-kotest5/src/main/kotlin/io/micronaut/test/extensions/kotest5/MicronautKotest5Context.kt
- test-kotest5/src/test/kotlin/io/micronaut/test/kotest5/intercept/InterceptTest.kt
- test-kotest5/src/test/kotlin/io/micronaut/test/kotest5/intercept/TestInterceptor.kt
- test-spock/src/main/java/io/micronaut/test/extensions/spock/MicronautSpockExtension.java
I tried to implement the test method interceptor for Kotest by failed because the provided interceptor in Kotlin is suspended
> Add to the text context: test name and if the test method interceptor is supported

- gradle/libs.versions.toml
- test-junit5/build.gradle
The latest version which comes via micronaut gradle and native build tool plugins needs to be used.
> Removed hardcoded version of metadata repo

- gradle/libs.versions.toml
- test-bom/build.gradle
- test-kotest5/build.gradle
micronaut-test-kotest5 now uses and exposes kotest-bom
Related PR into micronaut-platform: https://github.com/micronaut-projects/micronaut-platform/pull/901
Closes #843
> Use and export kotest-bom for kotest dependencies management

- .editorconfig
- test-kotest5/src/main/kotlin/io/micronaut/test/extensions/kotest5/MicronautKotest5Context.kt
- test-kotest5/src/main/kotlin/io/micronaut/test/extensions/kotest5/MicronautKotest5Extension.kt
- test-kotest5/src/test/kotlin/io/micronaut/test/kotest5/IsolationModeTest.kt
Hi Micronaut folks!
~I think the application context should be closed when a Kotest spec finishes executing, otherwise the resources are not cleaned up.~
Kotest5Context needs to support multiple instances of specs. 
See bug report here: https://github.com/kotest/kotest/issues/3711
> Support multiple Kotest spec instances

- test-kotest5/src/main/kotlin/io/micronaut/test/extensions/kotest5/MicronautKotest5Extension.kt
- test-kotest5/src/test/kotlin/io/micronaut/test/kotest5/IsolationModeTest.kt
- test-kotest5/src/test/kotlin/io/micronaut/test/kotest5/NoContextsRetentionTest.kt
This addresses a memory leak caused by `MicronautKotest5Extension` retaining all created `MicronautKotest5Context` that in turn retain all `ApplicationContext`s
Closes #861
> MicronautKotest5Extension does not retain contexts anymore after test spec is done

- test-core/src/main/java/io/micronaut/test/support/sql/TestSqlAnnotationHandler.java
- test-junit5/src/test/java/io/micronaut/test/junit5/ApplicationStopTest.java
- test-junit5/src/test/java/io/micronaut/test/junit5/SqlDatasourceApplicationStopTest.java
The TestSqlAnnotationHandler tried to load a ResourceLoader bean even if there were no Sql annotations. This fails if the context has been stopped in the test.
This PR does 2 things:
1. It only tries to load the bean if it has work to do
2. If it has work to do, and the context is stopped, it logs a warning and skips processing the scripts
I believe master has already switched to the 4.4.0 micronaut release (next minor) so I attached it to that project
> fix: TestSqlAnnotationHandler fails if context stopped in test

- test-spock/src/main/java/io/micronaut/test/extensions/spock/MicronautSpockExtension.java
- test-spock/src/test/groovy/io/micronaut/test/spock/intercept/InterceptTestSpec.groovy
When a feature is using `@Unroll` (which is implicit in recent versions of Spock), we needed to add the interceptor to the iteration interceptor handler instead of the standard handler.
This bug was visible in #911 where specs that were parameterized did not properly revert the transaction between iterations.
Closes #911
> fix: add interceptor around parameterized features

- test-spock/src/main/java/io/micronaut/test/extensions/spock/MicronautSpockExtension.java
- test-spock/src/test/groovy/io/micronaut/test/spock/intercept/InterceptTestSpec.groovy
Backport of https://github.com/micronaut-projects/micronaut-test/pull/953 to the 4.2.1 patch release branch
> fix: add interceptor around parameterized features (#953)

- gradle/libs.versions.toml
- test-core/build.gradle
- test-junit5/build.gradle
- test-kotest5/build.gradle
- test-rest-assured/build.gradle
- test-spock/build.gradle
- test-suite-at-sql-jpa/build.gradle.kts
> Move junit libs to managed block.
